# Generated by Django 3.0.4 on 2020-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survived', '0002_auto_20200331_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survived',
            name='last_update',
            field=models.DateTimeField(default='2019-11-01 00:00'),
        ),
    ]
