# Generated by Django 3.0.4 on 2020-04-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survived', '0003_auto_20200402_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='survived',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
