# Generated by Django 3.0.4 on 2020-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survived', '0004_auto_20200410_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
    ]
