# Generated by Django 3.0.4 on 2020-04-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survived', '0005_auto_20200410_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='world',
        ),
    ]
