# Generated by Django 3.0.4 on 2020-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survived', '0006_remove_world_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survived',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
